version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Andrii2803
      MYSQL_DATABASE: hw3_meal
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build: ./api
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      PORT: 3001
      DB_CLIENT: mysql2
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Andrii2803
      DB_DATABASE_NAME: hw3_meal
      DB_USE_SSL: "false"

  app-next:
    build: ./app-next
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001

volumes:
  db-data:
