FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

# Збираємо фронтенд (якщо у тебе є build step)
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
